In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('Local_retail_market_estimates__restaurants__UK__monthly__August_2019_to_August_2024.csv')

In [3]:
df.head()

,Unnamed: 0,cardholder_location,cluster_group,month,mcg,market_spend_index,market_transactions_index,market_cardholders_index
0,0,LL21 0,0,201901,RESTAURANTS,356.633989,401.76331,449.133568
1,1,TR7 1,0,201901,RESTAURANTS,356.633989,401.76331,449.133568
2,2,TR8 4,0,201901,RESTAURANTS,356.633989,401.76331,449.133568
3,3,TR8 5,0,201901,RESTAURANTS,356.633989,401.76331,449.133568
4,4,TR7 3,0,201901,RESTAURANTS,356.633989,401.76331,449.133568

In [4]:
df.tail()

,Unnamed: 0,cardholder_location,cluster_group,month,mcg,market_spend_index,market_transactions_index,market_cardholders_index
566298,566298,W5 2,2009,202406,RESTAURANTS,19.161099,16.909687,22.113173
566299,566299,TW11 8,2010,202406,RESTAURANTS,702.284562,567.118797,710.995246
566300,566300,TW11 0,2010,202406,RESTAURANTS,702.284562,567.118797,710.995246
566301,566301,DL16 7,2011,202406,RESTAURANTS,334.013957,413.744772,465.327404
566302,566302,DL16 6,2011,202406,RESTAURANTS,334.013957,413.744772,465.327404

In [5]:
df.shape

(566303, 8)